// Copyright (c) 2025 Doppleddiggong. All rights reserved. Unauthorized copying, modification, or distribution of this file, via any medium is strictly prohibited. Proprietary and confidential.


#include "ALingoGameState.h"

#include "Net/UnrealNetwork.h"
#include "APlayerActor.h"
#include "GameLogging.h"
#include "ULingoGameHelper.h"
#include "UBroadcastManager.h"
#include "UPopupManager.h"
#include "UPopup_MsgBox.h"
#include "UPopup_ReadQuest.h"
#include "ANetworkBroadcastActor.h"
#include "APlayerControl.h"
#include "IMediaControls.h"
#include "UMainWidget.h"
#include "GameFramework/PlayerController.h"
#include "Engine/World.h"

ALingoGameState::ALingoGameState()
{
	RemainMissionTime = 0.f;
	bIsTimerActive = false;

	PrimaryActorTick.bCanEverTick = true;

	// RoomId, RoomLevel은  Host가 생성합니다
	RoomId = 0;
	RoomLevel = 1;
}

void ALingoGameState::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME(ALingoGameState, RemainMissionTime);
	DOREPLIFETIME(ALingoGameState, bIsTimerActive);
	DOREPLIFETIME(ALingoGameState, QuestType);
	DOREPLIFETIME(ALingoGameState, RoomId);
	DOREPLIFETIME(ALingoGameState, RoomLevel);

	DOREPLIFETIME(ALingoGameState, ReadScenarioData);
	DOREPLIFETIME(ALingoGameState, WrongReadAnswerList);
	DOREPLIFETIME(ALingoGameState, ReqReadResult);
	DOREPLIFETIME(ALingoGameState, ReadResult);

	DOREPLIFETIME(ALingoGameState, ListenScenarioData);
	DOREPLIFETIME(ALingoGameState, WrongListenAnswerList);
	DOREPLIFETIME(ALingoGameState, ReqListenResult);
	DOREPLIFETIME(ALingoGameState, ListenResult);
	DOREPLIFETIME(ALingoGameState, TryListenAnswerData);
}

void ALingoGameState::BeginPlay()
{
	Super::BeginPlay();

	// Host(서버)만 RoomId를 생성합니다
	if (HasAuthority() && RoomId == 0)
	{
		this->RoomId = ULingoGameHelper::GetUnixTimestampInt64();

		// TODO임시
		this->RoomLevel = 2;
		
		PRINTLOG(TEXT("[LingoGameState] RoomId generated by Host: %lld"), RoomId);
	}
}

void ALingoGameState::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	// 서버에서만 타이머 처리
	if (!HasAuthority() || !bIsTimerActive)
		return;

	RemainMissionTime -= DeltaSeconds;

	if (RemainMissionTime <= 0.f)
	{
		RemainMissionTime = 0.f;
		OnMissionTimerEnd();
	}
}

void ALingoGameState::AddWrongReadAnswer(const int32 InValue)
{
	if (!WrongReadAnswerList.Contains(InValue))
	{
		WrongReadAnswerList.Add(InValue);
	}
}

void ALingoGameState::AddWrongListenAnswer(const int32 InValue)
{
	if (!WrongListenAnswerList.Contains(InValue))
	{
		WrongListenAnswerList.Add(InValue);
	}
}

void ALingoGameState::SetReadScenarioData( const FResponseReadScenario& InResponseData)
{
	// 반드시 서버 전용
	if (!HasAuthority())
		return;
	
	this->QuestType = EQuestType::Read;
	this->ReadScenarioData = InResponseData;

	// 미션 타이머 시작
	this->StartMissionTimer( ULingoGameHelper::GetMissionPlayTime() );

	if (HasAuthority())
	{
		Multicast_UpdateQuestType(QuestType);
		Multicast_ShowReadQuestPopup(ReadScenarioData);
	}
}

void ALingoGameState::SetListenScenarioData( const FResponseListenScenario& InResponseData)
{
	// 반드시 서버 전용
	if (!HasAuthority())
		return;
	
	this->QuestType = EQuestType::Listen;
	this->ListenScenarioData = InResponseData;

	// 미션 타이머 시작
	this->StartMissionTimer( ULingoGameHelper::GetMissionPlayTime() );

	if (HasAuthority())
	{
		Multicast_UpdateQuestType(QuestType);
		Multicast_ShowListenQuestPopup(ListenScenarioData);
	}
}

void ALingoGameState::StartMissionTimer(float InTimeLimit)
{
	// 서버에서만 실행
	if (!HasAuthority())
		return;

	this->TimeLimit = InTimeLimit;
	this->RemainMissionTime = InTimeLimit;
	this->bIsTimerActive = true;

	if (ANetworkBroadcastActor* BroadcastActor = ANetworkBroadcastActor::Get(this))
		BroadcastActor->SendUpdateMissionTimerState(true, InTimeLimit, this);
}

void ALingoGameState::StopMissionTimer()
{
	if (!HasAuthority())
		return;

	bIsTimerActive = false;

	// NetworkBroadcastActor를 통해 모든 클라이언트에 타이머 중지 알림
	if (ANetworkBroadcastActor* BroadcastActor = ANetworkBroadcastActor::Get(this))
	{
		BroadcastActor->SendUpdateMissionTimerState(false, 0.0f, this);
	}
}

void ALingoGameState::DecreaseMissionTimer(const float InValue)
{
	this->RemainMissionTime = FMath::Max(0.f, RemainMissionTime - InValue);
}

void ALingoGameState::UpdateRemainMissionTime(const float InTimeLimit)
{
	this->TimeLimit = InTimeLimit;
	this->RemainMissionTime = InTimeLimit;
}

void ALingoGameState::OnMissionTimerEnd()
{
	if (!HasAuthority())
		return;

	bIsTimerActive = false;

	// NetworkBroadcastActor를 통해 모든 클라이언트에 타이머 종료 알림
	if (ANetworkBroadcastActor* BroadcastActor = ANetworkBroadcastActor::Get(this))
		BroadcastActor->SendUpdateMissionTimerState(false, 0.0f, this);

	auto EndMessage = ULingoGameHelper::GetStageEndMessage(QuestType);

	PRINTLOG( TEXT("[GameState] Mission Timer Ended - Sending: %s"), *EndMessage);

	// 모든 플레이어에게 메시지 전송
	if (UWorld* World = GetWorld())
	{
		for (FConstPlayerControllerIterator It = World->GetPlayerControllerIterator(); It; ++It)
		{
			if (APlayerController* PC = It->Get())
			{
				if (APlayerActor* PlayerActor = Cast<APlayerActor>(PC->GetPawn()))
				{
					PlayerActor->OnGameMessage(EndMessage);
				}
			}
		}
	}
}


void ALingoGameState::Multicast_UpdateQuestType_Implementation(const EQuestType InQuestType)
{
	// 0.5초 딜레이 후 팝업 표시
	if (UWorld* World = GetWorld())
	{
		FTimerHandle TimerHandle;
		World->GetTimerManager().SetTimer(TimerHandle, [this, InQuestType]()
		{
			OnQuestScenarioDataUpdated.Broadcast();
		}, 0.5f, false);
	}
}


void ALingoGameState::Multicast_ShowReadQuestPopup_Implementation(const FResponseReadScenario& InScenarioData)
{
	// 0.5초 딜레이 후 팝업 표시 (플레이어 Role 동기화를 위함)
	if (UWorld* World = GetWorld())
	{
		FTimerHandle TimerHandle;
		World->GetTimerManager().SetTimer(TimerHandle, [this, InScenarioData]()
		{
			for (FConstPlayerControllerIterator It = GetWorld()->GetPlayerControllerIterator(); It; ++It)
			{
				if (APlayerController* PC = It->Get())
				{
					if (APlayerActor* PlayerActor = Cast<APlayerActor>(PC->GetPawn()))
					{
						PlayerActor->Cmd_Info();
					}
				}
			}
			
		}, 0.5f, false);
	}
}

void ALingoGameState::Multicast_ShowListenQuestPopup_Implementation(const FResponseListenScenario& InScenarioData)
{
	// 0.5초 딜레이 후 팝업 표시 (플레이어 Role 동기화를 위함)
	if (UWorld* World = GetWorld())
	{
		FTimerHandle TimerHandle;
		World->GetTimerManager().SetTimer(TimerHandle, [this, InScenarioData]()
		{
			for (FConstPlayerControllerIterator It = GetWorld()->GetPlayerControllerIterator(); It; ++It)
			{
				if (APlayerController* PC = It->Get())
				{
					if (APlayerActor* PlayerActor = Cast<APlayerActor>(PC->GetPawn()))
					{
						PlayerActor->Cmd_Info();
					}
				}
			}
			
		}, 0.5f, false);
	}
}

void ALingoGameState::OnRep_ReadScenarioData()
{
	OnQuestScenarioDataUpdated.Broadcast();
}

void ALingoGameState::OnRep_ReadResult()
{
	OnReadResultUpdated.Broadcast(ReadResult);
}

void ALingoGameState::OnRep_ListenScenarioData()
{
	OnQuestScenarioDataUpdated.Broadcast();
}

void ALingoGameState::OnRep_ListenResult()
{
	OnListenResultUpdated.Broadcast(ListenResult);
}

void ALingoGameState::OnRep_RoomId()
{
	OnRoomIdUpdated.Broadcast(RoomId);
}

void ALingoGameState::OnRep_RoomLevel()
{
	OnRoomLevelUpdated.Broadcast(RoomLevel);
}

void ALingoGameState::MulticastRPC_SendChat_Implementation(const FText& inMessage)
{
	// MainWidget의 SendChatMessage() 함수 호출
	if (auto* PC = Cast<APlayerControl>(GetWorld()->GetFirstPlayerController()))
	{
		// PRINTLOG(TEXT("[SendChat] ALingoGameState::MulticastRPC_SendChat - %s"), *inMessage.ToString());
		if (auto* player = Cast<APlayerActor>(PC->GetPawn()))
		{
			player->GetMainWidget()->SendChatMessage(inMessage);
		}
	}
}
